// flow-typed signature: 530ae408c94ce61a644b904f2b81f9e2
// flow-typed version: <<STUB>>/wake_on_lan_v^1.0.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wake_on_lan'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wake_on_lan' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wake_on_lan/wake_on_lan' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wake_on_lan/wake_on_lan.js' {
  declare module.exports: $Exports<'wake_on_lan/wake_on_lan'>;
}
